[workspace]
members = [
    "crates/lang-frontend",
    "crates/lang-codegen",
    "crates/lang-cli",
    "crates/lang-lsp",
    "crates/lang-std",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.96.0"
publish = false

[workspace.dependencies]
inkwell = { version = "0.10.0", default-features = false, features = ["llvm21-1-prefer-dynamic", "target-aarch64", "no-libffi-linking"] }
lang-codegen = { path = "crates/lang-codegen" }
lang-frontend = { path = "crates/lang-frontend" }

[workspace.lints.rust]
missing_docs = "warn"
unsafe_op_in_unsafe_fn = "deny"

[workspace.lints.clippy]
all = "warn"
